[language]
language = "zh_CN"

[[devices]]
host = "127.0.0.1"
port = 58526
agentPort = 10020
suMethod = "su -c"

[download]
codecAlternative = true
codecPriority = ["alac", "ec3", "ac3", "aac"]
atmosConventToM4a = true
songNameFormat = "{disk}-{tracknum:02d} {title}"
dirPathFormat = "downloads/{album_artist}/{album}"
saveLyrics = true
saveCover = true
coverFormat = "jpg"
afterDownloaded = ""

[metadata]
embedMetadata = ["title", "artist", "album", "album_artist", "composer",
    "genre", "created", "track", "tracknum", "disk", "lyrics", "cover", "copyright",
    "record_company", "upc", "isrc"]