on:
  push:
    branches:
    - master

jobs:
  build_winodws:
    name: Build Windows Version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install poetry
            poetry install
            poetry run python -m pip install nuitka
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          standalone: true
          include-data-dir: assets=assets
          include-data-files: |
            agent.js=agent.js
            config.toml=config.toml
      - name: Generate ZIP
        run: |
            ren main.dist AppleMusicDecrypt
            tar -a -cf AppleMusicDecrypt.zip AppleMusicDecrypt
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: AppleMusicDecrypt-Windows
          path: AppleMusicDecrypt.zip
          
