on:
  push:
    branches:
    - main

jobs:
  build_winodws:
    name: Build Windows Version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install poetry
            poetry install
            poetry run python -m pip install nuitka
      - name: Build
        run: |
            poetry run python -m nuitka main.py --standalone --follow-imports --include-data-dir=assets=assets --include-data-files=config.toml=config.toml --include-data-files=agent.js=agent.js
      - name: Generate ZIP
        run: |
            ren main.dist AppleMusicDecrypt
            tar -a -cf AppleMusicDecrypt.zip AppleMusicDecrypt
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: AppleMusicDecrypt-Windows
          path: AppleMusicDecrypt.zip
          
